const COLOR = {
  PRIMARY: '#014188',
  PRIMARY_LIGHT: '#E8F3FF',
  PRIMARY_DARK: '#022A55',
  SECONDARY: '#453823',
  SUCCESS: '#31D136',
  WARNING: '#FF9F1C',
  DANGER: '#FE0000',
  GRAY_DARK: '#707070',
  GRAY_LIGHT: '#EAEAEA',
  WHITE: '#FFFFFF',
};

const FONT_SIZE = {
  TITLE_PAGE_LARGE: 35,
  TITLE_PAGE_MEDIUM: 26,
  TITLE_PAGE_SMALL: 20,
  TITLE_LARGE: 16,
  TITLE_MEDIUM: 13,
  TITLE_SMALL: 9,
  TEXT_LARGE: 13,
  TEXT_MEDIUM: 12,
  TEXT_SMALL: 11,
};

const OPACITY = {
  PRIMARY: 1,
  SECONDARY: 0.75,
  TERTIARY: 0.5,
};

const FONT_WEIGHT = {
  BOLD: 'bold',
  NORMAL: '400',
  LIGHT: 'lighter',
};

export default {
  COLOR,
  FONT_SIZE,
  OPACITY,
  FONT_WEIGHT,
};
